### ISSUE TITLE
Tracking issue of tao interface for Gtk

### ISSUE THREAD

**Issue by wusyong** [tauri-apps/tao#10]
We are going to have a new unified interface to build window after tauri-apps/wry#163. It should cover most usage in Tauri.
But there are still many missing features for gtk. Below is the list of features (but not limited to):

- [ ] window methods (see [comment](https://github.com/tauri-apps/wry/issues/165#issuecomment-829008839) below)
- [ ] events (see [comment](https://github.com/tauri-apps/wry/issues/165#issuecomment-829012987) below)
- [x] platform traits (need to discuss what traits and methods are needed)
- [x] monitor module
  - [x] MonitorHandle
  - [x] VideoMode
