### ISSUE TITLE
Tracking issue for `tauri-hotkey` migration

### ISSUE THREAD

**Issue by lemarier** [tauri-apps/tao#33]
We should use https://github.com/tauri-apps/tauri-hotkey-rs

- [ ] Expose the manager somehow so tauri can re-use it
- [ ] Add new event type `Hotkey` or something similar
- [ ] Use `tauri-hotkey` for Windows menu accelerators
- [ ] Make sure accelerators sent to custom menu use `Hotkey` struct or string compatible with `tauri-hotkey`

**Comment by lucasfernog** [comment]
I think a good approach would be moving the key bindings from tauri-hotkey to a tauri-keys repo, and add a new formatting function, `to_gtk_string` or something like that. Then we can use it on both libs.
