### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by DiqahLer** [tauri-apps/tao#482]
# TODO
- [x] Update the CI with the proper node and npm versions
- [x] Update electron version
- [x] Update electron dependencies (electron-chromedriver and electron-mksnapshot) to match the electron version
- [x] Get the app to bootstrap on the new electron version
- [x] Once the build job passes make sure the artifacts are runnable/installable
- [x] Fix any failing tests and make sure the test jobs are passing on the CI
- [ ] Test the artifacts against the regression checklist below
- [ ] Check performance issue after upgrade on Linux (Check https://github.com/atom/atom/issues/20924 and the conversation below)

# BLOCKERS AND ISSUES
- [x] Failing github package tests
- [x] Project-wide find and replace not working.
- [x] macOS: Key binding with composition characters are ignored - alt-l inserting the `-` char
---

# Regression Checklist
## General testing

- [ ] Review issues tagged with [`electron`](https://github.com/search?utf8=%E2%9C%93&q=org%3Aatom+label%3Aelectron+is%3Aopen+is%3Aissue) to see if any of them are fixed

- [x] Verify that you can collaborate with Teletype
	- [x] Host using Atom's current stable release can collaborate with guest using Atom with the new version of Electron
	- [x] Guest using Atom's current stable release can collaborate with host using Atom with the new version of Electron
	- [x] Host and guest can collaborate when both are using Atom with the new version of Electron
  <details>
  <summary>Steps</summary>
	1. Open a file
	1. Share a portal
	1. Have a guest join the portal
	1. When guest edits the text in the file, verify that the host sees those changes
	</details>

### Text Input/Keybindings

See how to [setup keyboard layouts](https://github.com/atom/maintainers-log/blob/master/how-tos/setup-keyboard-layouts.md).

- [ ] IME not working (https://github.com/atom/atom/issues/14911)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Install an IME layout, for example Pinyin simplified  
  1. Open Atom and use the layout you installed as the keyboard layout
  1. Example, if you picked Pinyin simplified type in `zhongwenshuru`

  **Expected:** in Pinyin simplified `中文输入` is expected

  ![gif](https://user-images.githubusercontent.com/14314532/27643849-ccf636da-5c54-11e7-9111-e7b09469cf10.gif)

  **Issues we've seen:** Only shows latin first character and not every character typed.

  ![gif](https://user-images.githubusercontent.com/14314532/27643959-0f04396e-5c55-11e7-838c-ac15ef580fbe.gif)
  </details>

- [x] macOS: Key binding with composition characters are ignored (https://github.com/atom/atom/issues/15189)
  <details>
  <summary>Repro steps</summary>

  1. Open your keymap.cson file and add the following:
      ```cson
      'atom-text-editor':
        # use hjkl; vim-like when pressing alt (word by word, paragraph by paragraph)
        # or alt (letter by letter)
        'alt-h': 'core:move-left'
        'alt-j': 'core:move-down'
        'alt-k': 'core:move-up'
        'alt-l': 'core:move-right'
      ```
  1. Save keymap.cson and reload atom.
  1. Try the new keymappings under `ABC - Extended` keyboard layout

  **Expected**: the keybindings work

  **Issues we've seen:** it types out the modified keys and ignores the key mapping
  </details>

- [x] macOS: Composition characters mess up insertion point (https://github.com/atom/atom/issues/15344)
  <details>
  <summary>Repro steps</summary>

  1. Open keymap.cson and add the following:
      ```cson
      'atom-text-editor':
        'alt-n': 'core:move-down'
        'alt-o': 'core:move-down'
      ```
  1. Have the following in your buffer:
      ```
      Foo
      Bar
      ```
  1. Have the cursor at the beginning of file(before F character) Type alt-n, then arrow right, then insert a character. Observe that the character is inserted at the beginning of the line (where the alt-n left you).
  1. Repeat steps using <kbd>alt-o</kbd> instead of <kbd>alt-n</kbd>.

  **Expected**: Both alt-o and alt-n behave the same

  **Issues we've seen:**
  ![bug](https://user-images.githubusercontent.com/5624870/29386722-ebe4c2f6-8291-11e7-88e7-12cc89376cc7.gif)

- [ ] Ubuntu: Keystrokes involving <kbd>ctrl</kbd> resolve to the default layout instead of the active layout (https://github.com/atom/atom/issues/13170)

  <details>
  <summary>Repro steps</summary>

  **This should be tested on Linux with gnome**

  1. Install a Linux ditro with gnome, for example Ubuntu
  1. Install French AZERTY and English US QWERTY layouts
  1. Change the default layout to be French AZERTY
  1. Open Atom and switch to English US QWERTY layout
  1. Press ctrl-w

  **Expected**: `core:close` to dispatch (Or the keybinding-resolver to resolve to ctrl-w). Should be resolving to the keyboard layout that is chosen and not the OS default layout.

  **Issues we've seen:** `core:undo` dispatched because it was resolved as ctrl-z because AZERTY has Z where W is on QWERTY.
  </details>

- [x] Other keyboard layouts on new Electron version
  - [x] macOS: ABC - Extended
  - [x] macOS: Slovak
  - [x] macOS: U.S. International
  - [x] macOS: Squirrel (https://github.com/rime/squirrel)
  - [x] macOS: Full-Width Alphanumeric (Google) - Japanese layout  (https://www.google.co.jp/ime/)
  - [x] Windows: U.S.
  - [x] Linux: Pinyin Simplified

### UI

- [x] tree-view drag image (https://github.com/atom/tree-view/pull/1054)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open a project in Atom with multiple files and a few folders
  1. Drag a file into a folder

  **Expected:**  
  ![image](https://cloud.githubusercontent.com/assets/482957/24454969/3b9e370e-148e-11e7-8757-53171cd6d8e3.png)

  **Issues we've seen:**

  ![image](https://user-images.githubusercontent.com/5624870/30718615-465457ce-9ed5-11e7-96e2-b367fc4d0589.gif)
  </details>

- [x] drag-and-drop indicator (https://github.com/atom/tree-view/pull/1055, https://github.com/atom/tabs/pull/426, https://github.com/atom/tabs/pull/437)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open Atom with a few folder projects on tree-view (you can do this on terminal in a directory that has existing folder and having a space between each folder. Example: `atom folderA folderB folderC`)
  1. Drag and drop all of the folders to reorder them on Atom

  **Expected:**
  The placeholder indicates where the folder/project is being dropped to.

  ![screen shot 2017-03-29 at 16 31 16](https://cloud.githubusercontent.com/assets/482957/24459995/3e78d498-149d-11e7-8037-dab5a8312822.png)

  **Issues we've seen:**
  No placeholder shows up after drag and dropping

  ![screen shot 2017-03-29 at 16 30 51](https://cloud.githubusercontent.com/assets/482957/24459997/3e9f6b1c-149d-11e7-97c5-683aaa18221a.png)
  </details>

- [x] Large file rendering (https://github.com/atom/atom/issues/16591)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open a file that has over one million lines
  1. Scroll down to the bottom

  **Expected:** To not regress the number of lines that can be rendered. Rendering to be correct for lines past a certain point. Atom 1.25  can render around 800k to 1 million lines correctly.

  **Issues we've seen:** Increased number of lines rendered but bad rendering past a certain point

  ![bad renderer](https://user-images.githubusercontent.com/1058982/35113772-f2ffceda-fc82-11e7-81b6-6419c42ef3b4.gif)
  </details>

- [x] Loss of subpixel AA when the cursor is at the end of long lines (https://github.com/atom/atom/issues/16889, https://github.com/atom/atom/pull/16595)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open [text-editor.js](https://github.com/atom/atom/blob/2e19cf4a7c0a4d624b1f9c1072cd292de112cdb0/src/text-editor.js) in Atom
  1. Copy the first 21 lines to a new untitled window
  1. Turn on soft wrapping and change language mode to javascript
  1. Resize the Window so it's soft wrapped
  1. On line 15 type `a` until the you reach the end of the window

  **Expected:** To not lose subpixel AA

  **Issues we've seen:** Loss of subpixel AA. Both when soft wrapping was [enabled](https://github.com/atom/atom/pull/16943) and [disabled](https://github.com/atom/atom/pull/16595).

  ![subpixel aa loss softwrap](https://user-images.githubusercontent.com/1058982/37170628-a3901da0-230b-11e8-991e-c302db473eb3.gif)
  </details>

- [x] Scrolling horizontally shift + scroll wheel (https://github.com/atom/atom/pull/12696#issuecomment-288615912)
	- [x] macOS
	- [x] Windows 10
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open a file that has long lines
  1. Turn off soft wrapping and resize the window so you have a horizontal scrollbar
  1. Press shift and scroll in both directions using the mouse wheel

  **Expected:** File to scroll horizontally in both directions

  **Issues we've seen:** File does not scroll horizontally at all in any direction
  </details>

- [x] Scrollbars misbehaving on the first file that is opened (https://github.com/atom/atom/pull/12696#issuecomment-251299649)
  <details>
  <summary>Repro steps</summary>

  1. Open Atom
  1. Open some file that has content enough to have a vertical scrollbar
  1. Close Atom
  1. Open Atom and look at the vertical scrollbar

  **Expected:** Scrollbar to be visible

  **Issues we've seen:** Scrollbar is not visible and is flickering when you are editing
  </details>

- [x] Middle clicking on unsaved tab (https://github.com/atom/atom/issues/15197)
	- [x] macOS
	- [x] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Open Atom and open a new unsaved file.
  1. Make edits to the unsaved file and middle click on the tab.

  **Expected:**
  Clicking save/cancel or the options on the dialog works.

  **Issues we've seen:**
  The UI and the dialog is unable to receive mouse clicks. You can still choose options via Keyboard, but not mouse.
  </details>

- [x] Linux: Atom scrolls even when not focused (https://github.com/atom/atom/issues/15482)

  <details>
  <summary>Repro steps</summary>

  1. Open Atom with a large enough file that has a scrollbar
  1. Open a different application and place it over the Atom window
  1. Scroll with the mouse inside the other window
  1. Focus the Atom window

  **Expected:** Atom window should keep the original scroll position

  **Issues we've seen:** The Atom window scrolls after it is focused
  Note: this is a regression that has not been fixed since Electron 3, will leave it in the template to keep it on our radar once it's fixed 
  </details>

### Other

- [x] Supported Versions of OS (https://github.com/atom/atom/issues/15297)
	- [x] macOS
	- [ ] Windows 10
	- [ ] Ubuntu
  <details>
  <summary>Repro steps</summary>

  1. Check the list of supported platforms [Electron Master](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#supported-platforms)
  1. Check what version is listed as minimum for each platform on https://atom.io and https://atom.io/faq

  **Expected:** https://atom.io and https://atom.io/faq to display the same versions as the Electron documentation

  **Issues we've seen:** macOS version support changed and https://atom.io and https://atom.io/faq was not updated
  </details>

- [x] macOS : Native tabs (https://github.com/atom/atom/pull/14711)
  <details>
  <summary>Repro steps</summary>

  1. Open two atom windows on mac
  1. Go to View in menus and check `Show Tab Bar`
  ![screen shot 2017-06-03 at 5 10 32 pm](https://cloud.githubusercontent.com/assets/378023/26751932/aedfc05a-487f-11e7-9643-8047242b3bcb.png)
  1. Do this for both Atom windows.
  1. Drag one atom window to the other via tab bar

  **Expected:**
  Native Tab bar shows up and able to drag different windows to each other.  Also make sure UI isn't messed up.

  **Issues we've seen:**
  Native Tab Bar doesn't work and messes up UI when enabled
  </details>

- [ ] Ubuntu with KDE: Menu uses 100% CPU (https://github.com/electron/electron/issues/8455, https://github.com/atom/atom/issues/13885)
  <details>
  <summary>Repro steps</summary>

  1. Install Atom on Ubuntu KDE. [[instructions](https://linuxconfig.org/how-to-install-kde-plasma-desktop-on-ubuntu-18-04-bionic-beaver-linux)]
  1. Enable KDE plasma global menu: Right-click on the desktop -> Add Panel => Application Menu Bar. [[demo](https://youtu.be/qo5fhiXAUbI)]
  1. Start Atom.
  1. Try to use the desktop menu.

  **Expected:**
  Desktop menu items work

  **Issues we've seen:**
  Desktop menu items do nothing when you click on things.
  </details>

- [x] macOS: Slovak QWERTZ (https://github.com/atom/atom-keymap/issues/223)
  <details>
  <summary>Repro steps</summary>

  1. Install Slovak keyboard layout on mac
  1. Open keyboard viewer to see the keys are are suppose to show up and open keyboard resolver on atom.
  1. hit `cmd+'`.

  **Expected:**  Resolves to `cmd+'` like it shows on keyboard viewer on mac.

  **Issues we've seen:** It resolves to `ctrl+§`
  </details>

- [x] macOS: IME jump (https://github.com/atom/atom/issues/15696)
  <details>
  <summary>Repro steps</summary>

  1. Install an IME layout, for example Chinese pinyin
  1. Type one character

  **Expected:**
  Expected the IME to be positioned at under the character you entered
  **Issues we've seen:** The IME window is in the top left corner. When you enter the second character it jumps to be positioned under the text
  </details>

__Originally posted by @sadick254 in https://github.com/atom/atom/pull/22687__
